// Mock data for frontend development — replace with real API calls when backend is ready

export const mockJobs = [
  {
    id: 1,
    title: 'Senior Frontend Developer',
    company_name: 'TechCorp India',
    company_logo: null,
    location: 'Bangalore, Karnataka',
    job_type: 'Full-time',
    category: 'Technology',
    salary: '₹18,00,000 – ₹24,00,000/yr',
    salary_min: 1800000,
    salary_max: 2400000,
    created_at: '2025-01-10T09:00:00Z',
    description: `We are looking for a Senior Frontend Developer to join our growing engineering team. You will be responsible for building and maintaining high-quality web applications using React and modern frontend technologies.

You will collaborate closely with our product and design teams to deliver exceptional user experiences. The ideal candidate has a strong eye for design, writes clean maintainable code, and thrives in a fast-paced environment.`,
    requirements: [
      '5+ years of experience with React.js',
      'Strong proficiency in JavaScript/TypeScript',
      'Experience with state management (Redux, Zustand)',
      'Understanding of responsive design and CSS-in-JS',
      'Familiarity with REST APIs and GraphQL',
      'Experience with testing frameworks (Jest, Cypress)',
    ],
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'GraphQL', 'Node.js'],
    openings: 2,
    applicants: 47,
  },
  {
    id: 2,
    title: 'Product Manager',
    company_name: 'Zomato',
    company_logo: null,
    location: 'Gurugram, Haryana',
    job_type: 'Full-time',
    category: 'Management',
    salary: '₹20,00,000 – ₹30,00,000/yr',
    salary_min: 2000000,
    salary_max: 3000000,
    created_at: '2025-01-09T08:00:00Z',
    description: `Join Zomato as a Product Manager and drive the vision and roadmap for our core products. You will define product strategy, prioritize features, and work cross-functionally to deliver products that delight millions of users.

This is a high-impact role requiring strong analytical skills, user empathy, and the ability to drive alignment across engineering, design, and business teams.`,
    requirements: [
      '3+ years of product management experience',
      'Strong analytical and data-driven decision making',
      'Excellent communication and stakeholder management',
      'Experience with agile development methodologies',
      'Ability to translate business requirements to product specs',
    ],
    skills: ['Product Strategy', 'Agile', 'Data Analysis', 'User Research', 'Roadmapping'],
    openings: 1,
    applicants: 132,
  },
  {
    id: 3,
    title: 'Backend Engineer (Python)',
    company_name: 'Razorpay',
    company_logo: null,
    location: 'Bangalore, Karnataka',
    job_type: 'Full-time',
    category: 'Technology',
    salary: '₹22,00,000 – ₹32,00,000/yr',
    salary_min: 2200000,
    salary_max: 3200000,
    created_at: '2025-01-08T10:00:00Z',
    description: `Razorpay is hiring a Backend Engineer to build the infrastructure that powers India's leading payment gateway. You'll work on high-throughput, low-latency systems that process millions of transactions daily.

You will be part of a team that values engineering excellence, autonomy, and continuous learning. You will design, build, and maintain scalable backend services.`,
    requirements: [
      '3+ years of backend development with Python/Django',
      'Experience with distributed systems and microservices',
      'Strong knowledge of SQL and NoSQL databases',
      'Understanding of payment systems is a plus',
      'Experience with AWS/GCP cloud platforms',
    ],
    skills: ['Python', 'Django', 'PostgreSQL', 'Redis', 'Docker', 'AWS'],
    openings: 3,
    applicants: 89,
  },
  {
    id: 4,
    title: 'UI/UX Designer',
    company_name: 'Swiggy',
    company_logo: null,
    location: 'Remote',
    job_type: 'Remote',
    category: 'Design',
    salary: '₹12,00,000 – ₹18,00,000/yr',
    salary_min: 1200000,
    salary_max: 1800000,
    created_at: '2025-01-07T11:00:00Z',
    description: `Swiggy is looking for a talented UI/UX Designer to craft intuitive and beautiful experiences for our platform. You'll work on the design of our consumer-facing apps and internal tools.

You will conduct user research, create wireframes and prototypes, and collaborate with product and engineering teams to ship polished designs.`,
    requirements: [
      '2+ years of UI/UX design experience',
      'Proficiency in Figma and design tools',
      'Strong portfolio showcasing mobile and web projects',
      'Understanding of design systems and component libraries',
      'Experience with user research and usability testing',
    ],
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems', 'Mobile Design'],
    openings: 2,
    applicants: 63,
  },
  {
    id: 5,
    title: 'Data Scientist',
    company_name: 'Flipkart',
    company_logo: null,
    location: 'Bangalore, Karnataka',
    job_type: 'Full-time',
    category: 'Data Science',
    salary: '₹25,00,000 – ₹40,00,000/yr',
    salary_min: 2500000,
    salary_max: 4000000,
    created_at: '2025-01-06T09:30:00Z',
    description: `Flipkart's Data Science team is looking for a passionate Data Scientist to build models that drive personalization, recommendations, and supply chain optimization. You'll have access to one of India's largest e-commerce datasets.

You'll apply machine learning, statistical modeling, and data analysis to solve complex business problems at massive scale.`,
    requirements: [
      'Masters/PhD in Statistics, Computer Science, or related field',
      '2+ years of experience in ML/Data Science',
      'Proficiency in Python, R, and SQL',
      'Experience with ML frameworks (PyTorch, TensorFlow, scikit-learn)',
      'Strong statistical modeling and analysis skills',
    ],
    skills: ['Python', 'Machine Learning', 'TensorFlow', 'SQL', 'Statistics', 'Spark'],
    openings: 4,
    applicants: 201,
  },
  {
    id: 6,
    title: 'DevOps Engineer',
    company_name: 'Infosys',
    company_logo: null,
    location: 'Pune, Maharashtra',
    job_type: 'Full-time',
    category: 'Technology',
    salary: '₹10,00,000 – ₹16,00,000/yr',
    salary_min: 1000000,
    salary_max: 1600000,
    created_at: '2025-01-05T08:00:00Z',
    description: `Infosys is seeking a DevOps Engineer to streamline our development and deployment pipelines. You will work with development teams to implement CI/CD practices, manage cloud infrastructure, and ensure the reliability of production systems.`,
    requirements: [
      '3+ years of DevOps/infrastructure experience',
      'Strong knowledge of Docker, Kubernetes, and containerization',
      'Experience with CI/CD tools (Jenkins, GitLab CI, GitHub Actions)',
      'Proficiency with cloud platforms (AWS, Azure, GCP)',
      'Infrastructure as Code with Terraform or Ansible',
    ],
    skills: ['Docker', 'Kubernetes', 'AWS', 'Terraform', 'Jenkins', 'Linux'],
    openings: 5,
    applicants: 78,
  },
  {
    id: 7,
    title: 'Software Engineering Intern',
    company_name: 'Microsoft India',
    company_logo: null,
    location: 'Hyderabad, Telangana',
    job_type: 'Internship',
    category: 'Technology',
    salary: '₹60,000/month',
    salary_min: 60000,
    salary_max: 60000,
    created_at: '2025-01-04T10:00:00Z',
    description: `Microsoft India is offering a 6-month internship for passionate engineering students. You'll work alongside experienced engineers on real products that reach millions of users globally. This is a paid internship with potential for a full-time offer.`,
    requirements: [
      'Pursuing B.Tech/M.Tech in CS or related field',
      'Strong programming skills in C++, Java, or Python',
      'Good understanding of Data Structures and Algorithms',
      'Eagerness to learn and collaborate in a team environment',
    ],
    skills: ['Java', 'C++', 'Python', 'Data Structures', 'Algorithms'],
    openings: 10,
    applicants: 543,
  },
  {
    id: 8,
    title: 'Marketing Manager',
    company_name: 'Paytm',
    company_logo: null,
    location: 'Noida, Uttar Pradesh',
    job_type: 'Full-time',
    category: 'Marketing',
    salary: '₹14,00,000 – ₹20,00,000/yr',
    salary_min: 1400000,
    salary_max: 2000000,
    created_at: '2025-01-03T09:00:00Z',
    description: `Paytm is looking for a digital Marketing Manager to lead campaigns that acquire and retain millions of users. You'll own the digital marketing strategy, manage campaigns across channels, and analyze performance data to optimize ROI.`,
    requirements: [
      '4+ years of digital marketing experience',
      'Proficiency in Google Analytics, Meta Ads, and SEO tools',
      'Experience managing large marketing budgets',
      'Strong analytical skills and data-driven approach',
      'Understanding of fintech industry is a plus',
    ],
    skills: ['Digital Marketing', 'SEO/SEM', 'Google Analytics', 'Content Strategy', 'Email Marketing'],
    openings: 1,
    applicants: 94,
  },
  {
    id: 9,
    title: 'Android Developer',
    company_name: 'CRED',
    company_logo: null,
    location: 'Bangalore, Karnataka',
    job_type: 'Full-time',
    category: 'Technology',
    salary: '₹20,00,000 – ₹28,00,000/yr',
    salary_min: 2000000,
    salary_max: 2800000,
    created_at: '2025-01-02T11:00:00Z',
    description: `CRED is building India's most beautiful apps, and we want you to help us do it. As an Android Developer, you'll work on our award-winning app used by millions of credit card holders across India.`,
    requirements: [
      '3+ years of Android development experience',
      'Strong knowledge of Kotlin and Android SDK',
      'Experience with Jetpack Compose',
      'Understanding of MVVM/MVI architecture patterns',
      'Strong focus on performance and UI quality',
    ],
    skills: ['Kotlin', 'Android', 'Jetpack Compose', 'MVVM', 'Coroutines'],
    openings: 2,
    applicants: 112,
  },
  {
    id: 10,
    title: 'Content Writer (Part-time)',
    company_name: 'Byju\'s',
    company_logo: null,
    location: 'Remote',
    job_type: 'Part-time',
    category: 'Content',
    salary: '₹30,000 – ₹50,000/month',
    salary_min: 30000,
    salary_max: 50000,
    created_at: '2025-01-01T08:00:00Z',
    description: `Byju's is seeking a skilled Content Writer to create engaging educational content for our platform. You'll write articles, course descriptions, and marketing copy that helps millions of students learn better.`,
    requirements: [
      'Excellent written English',
      '1+ year of content writing experience',
      'Ability to explain complex topics simply',
      'Understanding of SEO best practices',
      'Self-motivated with ability to work remotely',
    ],
    skills: ['Content Writing', 'SEO', 'Research', 'Editing', 'WordPress'],
    openings: 3,
    applicants: 67,
  },
];

export const mockApplications = [
  {
    id: 1,
    job: mockJobs[0],
    status: 'Reviewing',
    applied_at: '2025-01-11T10:00:00Z',
    cover_letter: 'I am very excited about this opportunity...',
  },
  {
    id: 2,
    job: mockJobs[2],
    status: 'Applied',
    applied_at: '2025-01-10T14:30:00Z',
    cover_letter: 'I believe my experience with Python...',
  },
  {
    id: 3,
    job: mockJobs[6],
    status: 'Hired',
    applied_at: '2025-01-05T09:00:00Z',
    cover_letter: 'As a final year engineering student...',
  },
];

export const mockCompanyJobs = [
  { ...mockJobs[0], id: 1 },
  { ...mockJobs[1], id: 2, company_name: 'TechCorp India' },
];

export const jobCategories = [
  'Technology',
  'Design',
  'Marketing',
  'Management',
  'Data Science',
  'Finance',
  'Content',
  'Sales',
  'HR',
];

export const jobTypes = ['Full-time', 'Part-time', 'Remote', 'Internship', 'Contract'];

export const locations = [
  'Bangalore, Karnataka',
  'Mumbai, Maharashtra',
  'Delhi NCR',
  'Hyderabad, Telangana',
  'Pune, Maharashtra',
  'Chennai, Tamil Nadu',
  'Kolkata, West Bengal',
  'Remote',
];

export const mockUser = {
  id: 1,
  name: 'Arjun Sharma',
  email: 'arjun.sharma@email.com',
  role: 'applicant',
  phone: '+91 98765 43210',
  bio: 'Full-stack developer with 3 years of experience in React and Node.js.',
  skills: ['React', 'Node.js', 'Python', 'PostgreSQL'],
  resume: null,
  date_joined: '2024-09-01T00:00:00Z',
};

export const mockCompanyUser = {
  id: 2,
  name: 'Priya Nair',
  email: 'priya@techcorp.in',
  role: 'company',
  company_name: 'TechCorp India',
  company_description: 'A leading technology company building innovative solutions.',
  company_website: 'https://techcorp.in',
  date_joined: '2024-06-01T00:00:00Z',
};

export const featuredCompanies = [
  { name: 'Microsoft', color: 'from-blue-500 to-blue-600' },
  { name: 'Zomato', color: 'from-red-500 to-red-600' },
  { name: 'Razorpay', color: 'from-indigo-500 to-indigo-600' },
  { name: 'Swiggy', color: 'from-orange-500 to-orange-600' },
  { name: 'Flipkart', color: 'from-yellow-500 to-yellow-600' },
  { name: 'CRED', color: 'from-purple-500 to-purple-600' },
];
