# Generated by Django 4.2.9 on 2026-03-16 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('salary_min', models.PositiveIntegerField(default=0)),
                ('salary_max', models.PositiveIntegerField(default=0)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Remote', 'Remote'), ('Internship', 'Internship'), ('Contract', 'Contract')], default='Full-time', max_length=20)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Design', 'Design'), ('Marketing', 'Marketing'), ('Management', 'Management'), ('Data Science', 'Data Science'), ('Finance', 'Finance'), ('Content', 'Content'), ('Sales', 'Sales'), ('HR', 'HR')], default='Technology', max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('requirements', models.JSONField(blank=True, default=list)),
                ('openings', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(limit_choices_to={'role': 'company'}, on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
